security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: [app_patient_provider, app_praticien_provider]
        app_patient_provider:
            entity:
                class: App\Entity\Patient
                property: email
        app_praticien_provider:
            entity:
                class: App\Entity\Praticien
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            provider: chain_provider
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/logincheck
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator   
        main:
            anonymous: lazy
            provider: chain_provider
            guard:
               authenticators:
                    - App\Security\UserAuthentificatorAuthenticator
            logout:
                path: app_logout  
                target: /main

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logincheck, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }