-- 1
SELECT SUM(prixunit * ligne_com.QTECOM) AS total FROM ligne_com LEFT JOIN ARTICLE ON ARTICLE.IDARTICLE = ligne_com.IDARTICLE;

-- 2
SELECT SUM(prixunit * ligne_com.QTECOM) AS total FROM ligne_com LEFT JOIN ARTICLE ON ARTICLE.IDARTICLE = ligne_com.IDARTICLE GROUP BY ligne_com.NUMCOM;

-- 3
SELECT ligne_com.IDARTICLE, SUM(prixunit * ligne_com.QTECOM) AS total FROM ligne_com LEFT JOIN ARTICLE ON ARTICLE.IDARTICLE = ligne_com.IDARTICLE GROUP BY ligne_com.IDARTICLE ORDER BY total ASC;

-- 4
SELECT ARTICLE.IDARTICLE AS id_article FROM ligne_com LEFT JOIN ARTICLE ON ARTICLE.IDARTICLE = ligne_com.IDARTICLE WHERE ligne_com.QTECOM > 5;

-- 5
SELECT ARTICLE.IDARTICLE, ARTICLE.DESIGNATION, (ARTICLE.qtestock - SUM(ligne_com.QTECOM)) AS in_stock FROM ligne_com LEFT JOIN ARTICLE ON ARTICLE.IDARTICLE = ligne_com.IDARTICLE GROUP BY ARTICLE.IDARTICLE, ARTICLE.QTESTOCK, ARTICLE.DESIGNATION;

-- 6
UPDATE ARTICLE SET PRIXUNIT = PRIXUNIT + (PRIXUNIT * 2 / 100) WHERE PRIXUNIT < (SELECT AVG(PRIXUNIT) from ARTICLE);
COMMIT;

-- 7
SELECT ARTICLE.* FROM ARTICLE WHERE ARTICLE.QTESTOCK = (SELECT MAX(ARTICLE.QTESTOCK) FROM article);

-- 8
SELECT ARTICLE.IDARTICLE FROM ARTICLE WHERE PRIXUNIT < (SELECT AVG(ARTICLE.PRIXUNIT) FROM ARTICLE);